### ISSUE TITLE
Rich Presence 관전 버튼

### ISSUE THREAD

**Issue by wjdgustn** [pikokr/rhythmcraft2#20]
디스코드 화이트리스트 못들어가면 안됨 화이트 받으십시오

**Comment by patrick-mc** [comment]
화이트리스트 지금 안받고 있지 않나

**Comment by wjdgustn** [comment]
그러니까 내가 안만들었지

**Comment by patrick-mc** [comment]
ㅇㄴ 그럼 이슈 왜만든건데 닫는다

**Comment by patrick-mc** [comment]
https://support-dev.discord.com/hc/en-us/articles/360041437171
이거 풀리면 오픈 하세요
